### ISSUE TITLE
A question about the detectron2 version

### ISSUE THREAD

**Issue by higgsland** [JosephKJ/iOD#6]
The earliest official version of detectron2 only supports pytorch1.4[https://github.com/facebookresearch/detectron2/releases](url), And you are using pytorch1.3, what detectron2 version are you using, I will appreciate it if you answer as soon as possible!

**Comment by JosephKJ** [comment]
It works because PyTorch is quite forward-compatible. I am using the Detectron version that is bundled along with this repo. I dont exactly remember when I forked off. It would be somewhere around Nov 2019.
